[[language]]

name = "python"
language-servers = ["ruff-lsp", "pyright"]
indent = { tab-width = 4, unit = " " }

[language-server.pyright.config.python.analysis]
typeCheckingMode = "strict"

[language-server.ruff-lsp]
command = "ruff-lsp"

[language.formatter]
command = "ruff"
args = ["format", "-"]

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }
